### ISSUE TITLE
its not working 

### ISSUE THREAD

**Issue by Sunil23391** [peterjuras/sample-jspm-ts-sass#1]

**Comment by peterjuras** [comment]
Thanks for opening the issue, however this sample has only been created as a response for [this issue](https://github.com/dougludlow/plugin-sass/issues/25) and is not meant to be future proof and keep working.

I'm no longer actively working with a jspm / system-js stack, so I sadly can't say which version was used and how to get it working using an updated jspm / system-js version.

**Comment by Sunil23391** [comment]
Can you give me an hint what can i add to config file of the below url
https://embed.plnkr.co/gSkl9D/
which can work

**Comment by Sunil23391** [comment]
ok
